-- MySQL용 전국 아파트 통합 테이블 생성 스크립트
CREATE DATABASE IF NOT EXISTS aptdeal CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE aptdeal;

-- 아파트 기본 정보 테이블
CREATE TABLE IF NOT EXISTS apt (
  kaptCode VARCHAR(20) PRIMARY KEY,
  kaptName VARCHAR(100) NOT NULL,
  as1 VARCHAR(100),
  as2 VARCHAR(100),
  as3 VARCHAR(100),
  as4 VARCHAR(100),
  bjdCode VARCHAR(20),
  zipcode VARCHAR(20),
  kaptAddr VARCHAR(200),
  codeSaleNm VARCHAR(50),
  codeHeatNm VARCHAR(50),
  kaptTarea FLOAT,
  kaptDongCnt INT,
  kaptdaCnt VARCHAR(20),
  kaptBcompany VARCHAR(100),
  kaptAcompany VARCHAR(100),
  kaptTel VARCHAR(30),
  kaptFax VARCHAR(30),
  kaptUrl VARCHAR(200),
  codeAptNm VARCHAR(50),
  doroJuso VARCHAR(200),
  hoCnt INT,
  codeMgrNm VARCHAR(50),
  codeHallNm VARCHAR(50),
  kaptUsedate VARCHAR(20),
  kaptMarea FLOAT,
  kaptMparea60 FLOAT,
  kaptMparea85 FLOAT,
  kaptMparea135 FLOAT,
  kaptMparea136 FLOAT,
  privArea FLOAT,
  kaptTopFloor INT,
  ktownFlrNo INT,
  kaptBaseFloor INT,
  kaptdEcntp INT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_kaptName (kaptName),
  INDEX idx_as1 (as1),
  INDEX idx_as2 (as2),
  INDEX idx_as3 (as3),
  INDEX idx_bjdCode (bjdCode)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 아파트 실거래가 테이블
CREATE TABLE IF NOT EXISTS apt_deals (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  kaptCode VARCHAR(20) NOT NULL,
  aptname VARCHAR(100) NOT NULL,
  dong VARCHAR(50),
  jibun VARCHAR(50),
  area VARCHAR(50),
  floor INT,
  price BIGINT,
  dealYear INT,
  dealMonth INT,
  dealDay INT,
  dealDate DATE,
  cancelDate DATE,
  cancelType VARCHAR(10),
  regionCode VARCHAR(20),
  regionName VARCHAR(100),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_kaptCode (kaptCode),
  INDEX idx_aptname (aptname),
  INDEX idx_dealDate (dealDate),
  INDEX idx_regionCode (regionCode),
  INDEX idx_price (price),
  FOREIGN KEY (kaptCode) REFERENCES apt(kaptCode) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 아파트 전월세 테이블
CREATE TABLE IF NOT EXISTS apt_rents (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  kaptCode VARCHAR(20) NOT NULL,
  aptname VARCHAR(100) NOT NULL,
  dong VARCHAR(50),
  jibun VARCHAR(50),
  area VARCHAR(50),
  floor INT,
  rentType VARCHAR(10), -- '전세' 또는 '월세'
  deposit BIGINT,
  monthlyRent BIGINT,
  dealYear INT,
  dealMonth INT,
  dealDay INT,
  dealDate DATE,
  cancelDate DATE,
  cancelType VARCHAR(10),
  regionCode VARCHAR(20),
  regionName VARCHAR(100),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_kaptCode (kaptCode),
  INDEX idx_aptname (aptname),
  INDEX idx_dealDate (dealDate),
  INDEX idx_rentType (rentType),
  INDEX idx_regionCode (regionCode),
  FOREIGN KEY (kaptCode) REFERENCES apt(kaptCode) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci; 