-- Supabase(PostgreSQL)용 전국 아파트 통합 테이블 생성 스크립트
create table if not exists apt (
  kaptCode varchar(20) primary key,
  kaptName varchar(100),
  as1 varchar(100),
  as2 varchar(100),
  as3 varchar(100),
  as4 varchar(100),
  bjdCode varchar(20),
  zipcode varchar(20),
  kaptAddr varchar(200),
  codeSaleNm varchar(50),
  codeHeatNm varchar(50),
  kaptTarea float,
  kaptDongCnt int,
  kaptdaCnt varchar(20),
  kaptBcompany varchar(100),
  kaptAcompany varchar(100),
  kaptTel varchar(30),
  kaptFax varchar(30),
  kaptUrl varchar(200),
  codeAptNm varchar(50),
  doroJuso varchar(200),
  hoCnt int,
  codeMgrNm varchar(50),
  codeHallNm varchar(50),
  kaptUsedate varchar(20),
  kaptMarea float,
  kaptMparea60 float,
  kaptMparea85 float,
  kaptMparea135 float,
  kaptMparea136 float,
  privArea float,
  kaptTopFloor int,
  ktownFlrNo int,
  kaptBaseFloor int,
  kaptdEcntp int,
  created_at timestamp default now()
); 